### ISSUE TITLE
Loading on Unity

### ISSUE THREAD

**Issue by umanzoor-SE** [GeneralProtectionFault/InputLocalMultiplayerTemplate#1]
So when I try to load this downloaded project on unity It takes so much time and keeps showing the resolving packages window.
I have tried many unity versions but not solved Can you resolve it or have and solution just write here Thank you!

**Comment by GeneralProtectionFault** [comment]
This is not really an error, I don't think, but simply the necessity of downloading the libraries, and possibly an unfortunate consequence of a slow internet connection.  The project is around 2 MB without the libraries, and Unity will automatically resolve those, which adds another 500-600 MB to it at present.  It's necessary on the first loading of the project.  I could include the libraries in the repository, but then you'd just have to download the same amount from here instead of Unity doing it.
